### ISSUE TITLE
support argument `placeholder` for `DatePicker.shinyInput()` 

### ISSUE THREAD

**Issue by kyle-power** [Appsilon/shiny.fluent#106]
Referring to Microsoft FluentUI documentation: https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker

![image](https://user-images.githubusercontent.com/79020902/146083890-1e6e7838-041d-4c14-9158-80c228acd4f4.png)

Currently, `DatePicker.shinyInput()` defaults to a value of current date if not specified. I am not able to use the `placeholder` argument to fill with text. Always defaults to current date of system.

I would like the DatePicker to have `null` value with text string "Select a date..."

**Comment by kamilzyla** [comment]
Thanks for reporting this @kyle-power! We have a related issue #51; these two should be considered together.
