### ISSUE TITLE
Part of the UI doesn't have any functionality

### ISSUE THREAD

**Issue by fernandoroa** [Appsilon/shiny.fluent#117]
In header (commandBar) and sidebar (iconButtons), there are several icons/iconButtons that don't do anything

Add a task or place them in the corresponding example pages.

**Comment by konrad-appsilon** [comment]
I think that it is not the main part of the demo but indeed some parts of the UI don't have any functionality. Maybe it is worth hiding them. 
![image](https://user-images.githubusercontent.com/98808247/153003965-294653f3-a1ef-4eba-97a7-7fa7274d58fb.png)

**Comment by konrad-appsilon** [comment]
I got confirmation it is mocked on purpose, I'm closing the issue.
