### ISSUE TITLE
how can i make the 'download' button in the command bar actually download something?

### ISSUE THREAD

**Issue by mattrichard-datascience** [Appsilon/shiny.fluent#124]
there doesn't appear to be anyway that clicking the button can cause a reactive or observed event. Are these shiny.fluent command icons just for looks? are they actually usable?

could you provide an example please?

Thanks!
Matt

**Comment by jakubsob** [comment]
Hello @mattrichard-datascience,

The feature you're describing is already a feature request, please take a look at this issue #44 for a workaround
