### ISSUE TITLE
how can i make the 'download' button in the command bar actually download something?

### ISSUE THREAD

**Issue by mattrichard-datascience** [Appsilon/shiny.fluent#125]
how can i make the 'download' button in the command bar actually download something?

**Comment by kyle-power** [comment]
Hey! Try this example: https://github.com/Appsilon/shiny.fluent/issues/39

**Comment by mattrichard-datascience** [comment]
That example seemed to be making a new commandbar. Is there a way to use the built in 'fluent-ui' command bar (see arrow pointing to command bar button in attached image)

![commandbar button](https://user-images.githubusercontent.com/11857669/158803715-3263ed0b-04f9-4d81-9596-a0669ad7f4cd.jpg)

**Comment by jakubsob** [comment]
Hi @mattrichard-datascience,

The communication between CommandBar and Shiny is not implemented yet. The easiest workaround is to create your own command bar from scratch using ActionButtons. See this issue #44. 

Download button is also not yet supported, please use workaround mentioned in #39 for now.
