### ISSUE TITLE
Not rendering the content in the second PivotItem

### ISSUE THREAD

**Issue by justacec** [Appsilon/shiny.fluent#191]
### Code example

```
library(shiny.fluent)
library(shiny)
library(reactable)

mod_ui = function(id) {
    ns = NS(id)

    tagList(
        reactableOutput(ns('table_out'))
    )
}

mod_server = function(id) {
    moduleServer(id, function(input, output, session) {
        output$table_out = renderReactable({
            pd = iris
            reactable(pd)
        })
    })
}

ui = function() {
    fluentPage(
        Pivot(
            PivotItem(id = 'test1', alwaysRender = TRUE, headerText = 'Test 1 Pivot', itemKey = 'test1', mod_ui('tab1')),
            PivotItem(id = 'test2', alwaysRender = TRUE, headerText = 'Test 2 Pivot', itemKey = 'test2', mod_ui('tab2'))            
        )
    )
}

server = function(input, output, session) {
    mod_server('tab1')
    mod_server('tab2')
}

shiny::runApp(shiny::shinyApp(ui = ui, server = server), launch.browser = FALSE)

```

### Bug description

In this example, the content of the second PivotItem is not rendred.  If I set `alwaysRender` to `FALSE`, the two panes do render.

### Expected behavior

Both PivotItem's would render correctly

### Comments

> version
               _
platform       x86_64-w64-mingw32
arch           x86_64
os             mingw32
crt            ucrt
system         x86_64, mingw32
status
major          4
minor          2.0
year           2022
month          04
day            22
svn rev        82229
language       R
version.string R version 4.2.0 (2022-04-22 ucrt)
nickname       Vigorous Calisthenics

shiny.fluent: 0.3.0

**Comment by justacec** [comment]
In general, it seems that anything in the later PivotItems (not the first one) do not render.

**Comment by jakubsob** [comment]
Hi @justacec,

This component is working as expected. Please consider those 2 cases. I inspect the DOM before clicking on any pivot item.

#### `alwaysRender=TRUE`

<img width="1437" alt="image" src="https://github.com/Appsilon/shiny.fluent/assets/37193264/e1efb29f-d447-488e-8a91-e653a3bf2048">

In the DOM we can see that content of the pivot has been rendered correctly. It contains `<div id="test2" ...`.

#### `alwaysRender=FALSE`

<img width="1437" alt="image" src="https://github.com/Appsilon/shiny.fluent/assets/37193264/c6975e34-83f1-4c3b-a423-d11f7e23122a">

With `alwaysRender = FALSE` we have nodes only for first pivot item.

This is the correct behavior that we would expect in Shiny. What we see rendered with `alwaysRender = TRUE` is `reactableOutput(ns('table_out'))`. When Shiny elements are hidden their corresponding server part is not run - this is a default Shiny behavior - you usually don't want to recalculate outputs that are hidden to have better performance. To opt-out from this default behavior you can set `suspendWhenHidden = FALSE` on given output elements. Please consider the updated example - it renders tables in all tabs.

```r
library(shiny.fluent)
library(shiny)
library(reactable)

mod_ui = function(id) {
  ns = NS(id)
  tagList(
    reactableOutput(ns('table_out'))
  )
}

mod_server = function(id) {
  moduleServer(id, function(input, output, session) {
    output$table_out = renderReactable({
      pd = iris
      reactable(pd)
    })
    outputOptions(output, "table_out", suspendWhenHidden = FALSE)
  })
}

ui = function() {
  fluentPage(
    Pivot(
      PivotItem(id = 'test1', alwaysRender = TRUE, headerText = 'Test 1 Pivot', itemKey = 'test1', mod_ui('tab1')),
      PivotItem(id = 'test2', alwaysRender = TRUE, headerText = 'Test 2 Pivot', itemKey = 'test2', mod_ui('tab2'))            
    )
  )
}

server = function(input, output, session) {
  mod_server('tab1')
  mod_server('tab2')
}

shiny::runApp(shiny::shinyApp(ui = ui, server = server))
```

**Comment by justacec** [comment]
Cool.  Thanks for the feedback and I will integrate that.  Given that point, why is it that the table was not rendered when you click on the second tab which would make the outputs visible?

**Comment by justacec** [comment]
@jakubsob Did I miss something in your response that speaks to why the content does not render when the tab is un-hidden?  That is still an issue with the example code that I supplied.
