### ISSUE TITLE
The PivotItem resets state whenever the tab is changed

### ISSUE THREAD

**Issue by datatenk** [Appsilon/shiny.fluent#210]
### Code example

```
shinyApp(
  ui=fluentPage(
    Pivot(
      id='pivot',
      PivotItem(
        headerText='a_tab',
        Slider.shinyInput(inputId='a1',min=0,max=10,value=3)
      ),
      PivotItem(
        headerText='b_tab',
        checkboxInput('a2','a2')
      ),
    ),
    
    verbatimTextOutput('text')
    
  ),
  
  server=function(input,output,session){
    
    output$text<-renderText({
      paste0('a1=',input$a1,'\n',
             'a2=',input$a2)})
  
  }
)

```

### Bug description

Initial load, a1=3, a2=False, active tab = "tab_a".
Slide the slider, watch the a1 variable change, stop at a1=5.
Go to tab "tab_b", check the check box, a2=True.
Go back to tab "tab_a", a1 variable is reset to default value, a1=3.
Go back to tab "tab_b", a2 variable is reset to default value, a2=False.

### Expected behavior

On switching tabs, a1 and a2 should hold the last value.

### Comments

I deliberately use both shiny and shiny.fluent input functions (Slider.shinyInput and checkBoxInput) in my example to demonstrate that this is not a problem with either of those controls, something is up with "Pivot" or "PivotItem".

**Comment by radovan-miletic** [comment]
Hi @datatenk,
Try using additional argument:
`PivotItem(alwaysRender = TRUE,`
which "defines whether to always render the pivot item".
It may help.

**Comment by datatenk** [comment]
Thank you @radovan-miletic for the advice - it works. It would seem reasonable for the package authors to default the `alwaysRender` argument to `TRUE` in the next release, as it is a common gotcha for users adapting this new package coming from vanilla Shiny or bslib, where input variable holding its state following tab-switching is the norm.
