### ISSUE TITLE
Make `CommandBar` more intuitive to use

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/shiny.fluent#44]
It is relatively easy to render a `CommandBar` with some buttons, but it's quite hard to actually connect them to Shiny, i.e. get click events. A natural idea is to use `CommandBarButton.shinyInput` components, but it's not that simple. We should improve the example and/or think of some helpers / interface improvements to better support this use case.

**Comment by lorenzbr** [comment]
Have you made progress on this front? I am changing to the shiny.fluent UI, but indeed some things are relatively hard to grasp because there are very few or no examples. Can you please provide an example how to use the CommandBar with ActionButtons but also with rendering UI (similar to the Navbar page). Thanks!

**Comment by jakubsob** [comment]
Hi @lorenzbr,
unfortunately we haven't made any progress in this matter yet. As far as I'm concerned the easiest way now to achieve a the effect you're describing is by using buttons in a custom container and handle the page switching logic yourself:

```r
library(shiny)
library(shiny.fluent)

shinyApp(
  ui = fluentPage(
    div(
      style = "
        display: flex;
        flex-direction: row;
      ",    
      CommandBarButton.shinyInput("page1", text = "Page 1"),
      CommandBarButton.shinyInput("page2", text = "Page 2"),
      CommandBarButton.shinyInput("page3", text = "Page 3"),
      CommandBarButton.shinyInput("page4", text = "Page 4"),
      tags$script(
        "$(function() {
          $('.ms-Button--commandBar').on('click', function() {
            Shiny.setInputValue('activePage', $(this).attr('id'));
          })
        })"
      )
    ),
    uiOutput("content")
  ),
  server = function(input, output, session) {
    output$content <- renderUI({
      page <- if (is.null(input$activePage)) "page1" else input$activePage
      switch(
        page,
        "page1" = Label("This is page 1"),
        "page2" = Label("This is page 2"),
        "page3" = Label("This is page 3"),
        "page4" = Label("This is page 4")
      )
    })
  }
)
```

This is a crude workaround, but it works. Let us know if it would be a sufficient solution for you for now, until we're done with implementing `CommandBar`

**Comment by lorenzbr** [comment]
Thank you for this example. Unfortunately, this does not work for me when using your solution within shiny.fluent's CommandBar argument _items_. Am I doing something wrong here or can you reproduce this issue?

**Comment by jakubsob** [comment]
Hi @lorenzbr,

it's not possible at the moment to use `CommandBar` to achieve this functionality. I needs to be recreated using a custom container for the header buttons as provided in the example above.
