### ISSUE TITLE
Prepare shiny.fluent for CRAN submission

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/shiny.fluent#45]
Ensure that `R CMD check --as-cran` passes without any errors, warnings or notes. Update CI to fail on notes (currently it only fails on errors).

**Comment by jakubsob** [comment]
`R CMD check --as-cran` reports:
- 1 warning, mostly `Undocumented arguments in documentation object {Component}` and `Documented arguments not in \usage in documentation object {Component}`
- 3 notes:
  - package size exceeds allowed 5Mb 
    ```installed size is 10.8Mb
    sub-directories of 1Mb or more:
    doc   4.9Mb
    www   4.7Mb
     ```
  - `Unexported object imported by a ':::' call: ‘shiny:::resolve’`
  - Multiple: `\examples lines wider than 100 characters`

**Comment by jakubsob** [comment]
When components are generated using `shiny.fluent:::component` factory the `...` argument is not documented which results in e.g. `Undocumented arguments in documentation object 'Toggle' ‘...’`. It can be resolved using e.g.
```
# components.R

component <- function(name) {
  function(...) shiny.react::reactElement(
    module = "@fluentui/react", name = name,
    props = shiny.react::asProps(...),
    deps = shinyFluentDependency()
  )
}

#' Ellipsis documentation template
#' @name doc
#' @param ... Props to pass to \code{shiny.react::reactElement}. See allowed props listed below
NULL

#' @rdname Toggle
#' @inheritParams doc
#' @export
Toggle <- component("Toggle")
```

But then it prepends ellipsis to the list of arguments of every component

![Screenshot 2021-11-19 at 16 38 58](https://user-images.githubusercontent.com/37193264/142649712-52f2a320-7a85-4536-82c5-250bd105d920.png)

This is in line with actual usage of components as every prop needs to be passed as a named argument using ellipsis, but on the other hand documentation is actually "duplicated" as each prop is contained in ellipsis and it may be confusing. 

This "See allowed props listed below" comment may do the job IMO, but do you know any other way how to combine those arguments together in docs? @kamilzyla

**Comment by corinabioinformatic** [comment]
Is it any update about the CRAN submission? I tried to install the package for testing purposes from CRAN and it is yet not available (shiny.react it is). 

Many thanks,

Corina

**Comment by jakubsob** [comment]
Hi @corinabioinformatic,

submitting the package to CRAN is still in progress, but you can always install the package from GitHub using:
```
remotes::install_github("Appsilon/shiny.react")
remotes::install_github("Appsilon/shiny.fluent")
```

**Comment by jakubsob** [comment]
To close this issue those must be closed first:
- [ ] #122 
- [ ] #128 
- [ ] #99
