### ISSUE TITLE
Please add an example for Dropdown.shinyInput with multiple items all selected by default

### ISSUE THREAD

**Issue by mattrichard-datascience** [Appsilon/shiny.fluent#67]
preferably with an example showing;

1) all items originally selected by default
2) the ability to open the drop down menu and 'de-select' some items

Currently the documentation only shows example for 1 selection at a time.

You guys are the best!
Thanks,
Matt

**Comment by younessbahi** [comment]
same problem here, cannot select multiple items, no docs in it

**Comment by jakubsob** [comment]
Thanks @mattrichard-datascience, @younessbahi for submitting the issue! We'll look into it next week

**Comment by jakubsob** [comment]
I see now that it's basically the same issue as #42. Being able to select multiple elements in `Dropdown` is a feature we're still working on. Once this feature is added proper documentation on how to use will be added as well. We hope to add this feature soon enough.
