### ISSUE TITLE
Example not runnable

### ISSUE THREAD

**Issue by robertamezquita** [Appsilon/shiny.fluent#69]
Example will not run on latest versions of shiny.fluent/shiny.react

## Example application or steps to reproduce the problem

Add a minimal example that shows the issue (we recommend using the https://reprex.tidyverse.org/ package).

```r
shiny.fluent::runExample("demo")
shiny.fluent::runExample("dashboard")
# Error in router$ui : object of type 'closure' is not subsettable
```

### Expected behavior

Example runs.

### Actual behavior

Example does not run.

## Additional info

Place for any additional details that you would like to include.

**Comment by jakubsob** [comment]
Thanks @robertamezquita for submitting this bug! We'll take a look at it next week

**Comment by jakubsob** [comment]
Hello @robertamezquita! 

Now you should be able to run examples when having `shiny.fluent` installed using:
```
remotes::install_github("Appsilon/shiny.fluent", dependencies = TRUE)
```
This way all required packages for examples to run will be installed alongside `shiny.fluent`

**Comment by robertamezquita** [comment]
Thanks for the quick fix!
