### ISSUE TITLE
Dynamic response to screen sizes

### ISSUE THREAD

**Issue by shahreyar-abeer** [Appsilon/shiny.fluent#91]
As great as shiny.fluent is, it does not have dynamic response at the moment.
This is the app on a large screen.  
![image](https://user-images.githubusercontent.com/20732893/136143855-2bd94312-62c8-479f-bb09-499c8883a7b6.png)

The same app on a smaller screen.  
![image](https://user-images.githubusercontent.com/20732893/136143884-22c00e26-4515-453a-8df4-9edf6513dca5.png)

The navbar width, font-sizes etc. are the same in both screens.
As far as I understand, it is not dynamic to screen sizes yet.

Will this feature be added in the near future to make the excellent fluent app dynamic to all screen sizes, including mobile screens?

**Comment by jakubsob** [comment]
Hello @shahreyar-abeer, thanks for reaching out!

shiny.fluent is a package that supplies users with Fluent UI components, how those components can be arranged is a matter outside of scope of this package and won't be added in the future.

There are many ways to arrange components in Shiny apps and this one uses [CSS Grid Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout). This app was designed to have a navbar of fixed width as you can see in [style.scss file (line 14)](https://github.com/Appsilon/shiny.fluent/blob/master/inst/examples/dashboard/style.scss). To make navbar respond to changing width of window you could use such `.grid-container` class:

```
.grid-container {
  display: grid;
  grid-template-columns: 20% 80%;
  grid-template-rows: 54px 1fr 140px;
  grid-template-areas:
    "header header"
    "sidenav main"
    "footer footer";
  height: 100vh;
}
```

This would make navbar take 20% of the screen and it would scale as you change size of the window. 

I highly encourage you to play with our examples to find out how they were built. I hope they give you some insight into how to build beautiful, responsive Shiny apps!
